spring:
  elasticsearch:
    bboss:
      elasticPassword: changeme
      elasticUser: elastic
      elasticsearch: 
        rest:
          hostNames: 192.168.137.1:9200
        connectionRequestTimeout: 500
        timeoutConnection: 50000
        timeoutSocket: 50000         
        showTemplate: true        
      http:
        defaultMaxPerRoute: 200
        maxTotal: 400
        retryTime: 3
      
 