http.poolNames = deepseek,embedding_model

##Deepseek模型服务配置：在代码中引用服务的名称为deepseek
# 服务连接池参数
deepseek.http.maxTotal = 200
deepseek.http.defaultMaxPerRoute = 200
# Deepseek模型服务地址
deepseek.http.hosts=https://api.deepseek.com
#基于apiKeyId认证配置（主要用于各种大模型服务对接认证）
deepseek.http.apiKeyId = sk-33e139f9ec954ac9bfxxxxxxxx9d
# 模型类型：AI智能体工具通过模型类型查找智能体模型对接适配器
deepseek.http.modelType = deepseek
 

embedding_model.http.hosts = 10.13.6.7:9997

embedding_model.http.timeoutSocket = 600000
embedding_model.http.timeoutConnection = 400000
embedding_model.http.connectionRequestTimeout = 700000
embedding_model.http.maxTotal = 100
embedding_model.http.defaultMaxPerRoute = 100
embedding_model.http.modelType = xinference
 

